graph TD
    N0[__init__.py]
    N1[config_analyzer.py]
    N2[main.py]
    N3[demo_conflicts.py]
    N4[1_generate_skill.py]
    N5[2_upload_to_chroma.py]
    N6[3_query_example.py]
    N7[generate_clinerules.py]
    N8[context_server.py]
    N9[quickstart.py]
    N10[App.tsx]
    N11[index.tsx]
    N12[generate_cursorrules.py]
    N13[1_generate_skill.py]
    N14[2_build_faiss_index.py]
    N15[3_query_example.py]
    N16[quickstart.py]
    N17[quickstart.py]
    N18[quickstart.py]
    N19[quickstart.py]
    N20[1_generate_skill.py]
    N21[2_upload_to_qdrant.py]
    N22[3_query_example.py]
    N23[test_http_server.py]
    N24[1_generate_skill.py]
    N25[2_upload_to_weaviate.py]
    N26[3_query_example.py]
    N27[generate_windsurfrules.py]
    N28[__init__.py]
    N29[_version.py]
    N30[__init__.py]
    N31[framework.py]
    N32[models.py]
    N33[runner.py]
    N34[__init__.py]
    N35[__init__.py]
    N36[base.py]
    N37[chroma.py]
    N38[claude.py]
    N39[faiss_helpers.py]
    N40[gemini.py]
    N41[haystack.py]
    N42[langchain.py]
    N43[llama_index.py]
    N44[markdown.py]
    N45[openai.py]
    N46[qdrant.py]
    N47[streaming_adaptor.py]
    N48[weaviate.py]
    N49[ai_enhancer.py]
    N50[api_reference_builder.py]
    N51[architectural_pattern_detector.py]
    N52[benchmark_cli.py]
    N53[cloud_storage_cli.py]
    N54[code_analyzer.py]
    N55[codebase_scraper.py]
    N56[config_command.py]
    N57[config_enhancer.py]
    N58[config_extractor.py]
    N59[config_fetcher.py]
    N60[config_manager.py]
    N61[config_validator.py]
    N62[conflict_detector.py]
    N63[constants.py]
    N64[dependency_analyzer.py]
    N65[doc_scraper.py]
    N66[embedding_pipeline.py]
    N67[enhance_skill.py]
    N68[enhance_skill_local.py]
    N69[enhance_status.py]
    N70[estimate_pages.py]
    N71[generate_router.py]
    N72[github_fetcher.py]
    N73[github_scraper.py]
    N74[guide_enhancer.py]
    N75[how_to_guide_builder.py]
    N76[incremental_updater.py]
    N77[install_agent.py]
    N78[install_skill.py]
    N79[language_detector.py]
    N80[llms_txt_detector.py]
    N81[llms_txt_downloader.py]
    N82[llms_txt_parser.py]
    N83[main.py]
    N84[markdown_cleaner.py]
    N85[merge_sources.py]
    N86[multilang_support.py]
    N87[package_multi.py]
    N88[package_skill.py]
    N89[__init__.py]
    N90[analyze_parser.py]
    N91[base.py]
    N92[config_parser.py]
    N93[enhance_parser.py]
    N94[enhance_status_parser.py]
    N95[estimate_parser.py]
    N96[github_parser.py]
    N97[install_agent_parser.py]
    N98[install_parser.py]
    N99[multilang_parser.py]
    N100[package_parser.py]
    N101[pdf_parser.py]
    N102[quality_parser.py]
    N103[resume_parser.py]
    N104[scrape_parser.py]
    N105[stream_parser.py]
    N106[test_examples_parser.py]
    N107[unified_parser.py]
    N108[update_parser.py]
    N109[upload_parser.py]
    N110[pattern_recognizer.py]
    N111[pdf_extractor_poc.py]
    N112[pdf_scraper.py]
    N113[presets.py]
    N114[quality_checker.py]
    N115[quality_metrics.py]
    N116[rag_chunker.py]
    N117[rate_limit_handler.py]
    N118[resume_command.py]
    N119[run_tests.py]
    N120[setup_wizard.py]
    N121[signal_flow_analyzer.py]
    N122[split_config.py]
    N123[__init__.py]
    N124[azure_storage.py]
    N125[base_storage.py]
    N126[gcs_storage.py]
    N127[s3_storage.py]
    N128[streaming_ingest.py]
    N129[swift_patterns.py]
    N130[sync_cli.py]
    N131[test_example_extractor.py]
    N132[test_unified_simple.py]
    N133[unified_codebase_analyzer.py]
    N134[unified_scraper.py]
    N135[unified_skill_builder.py]
    N136[upload_skill.py]
    N137[utils.py]
    N138[__init__.py]
    N139[cache.py]
    N140[generator.py]
    N141[models.py]
    N142[server.py]
    N143[__init__.py]
    N144[agent_detector.py]
    N145[git_repo.py]
    N146[server.py]
    N147[server_fastmcp.py]
    N148[server_legacy.py]
    N149[source_manager.py]
    N150[__init__.py]
    N151[config_tools.py]
    N152[packaging_tools.py]
    N153[scraping_tools.py]
    N154[source_tools.py]
    N155[splitting_tools.py]
    N156[vector_db_tools.py]
    N157[__init__.py]
    N158[detector.py]
    N159[models.py]
    N160[monitor.py]
    N161[notifier.py]
    N162[test_api.py]
    N163[test_week2_features.py]
    N164[__init__.py]
    N165[conftest.py]
    N166[test_adaptor_benchmarks.py]
    N167[__init__.py]
    N168[test_adaptors_e2e.py]
    N169[test_base.py]
    N170[test_chroma_adaptor.py]
    N171[test_claude_adaptor.py]
    N172[test_faiss_adaptor.py]
    N173[test_gemini_adaptor.py]
    N174[test_haystack_adaptor.py]
    N175[test_langchain_adaptor.py]
    N176[test_llama_index_adaptor.py]
    N177[test_markdown_adaptor.py]
    N178[test_openai_adaptor.py]
    N179[test_qdrant_adaptor.py]
    N180[test_weaviate_adaptor.py]
    N181[test_analyze_command.py]
    N182[test_analyze_e2e.py]
    N183[test_api_reference_builder.py]
    N184[test_architecture_scenarios.py]
    N185[test_async_scraping.py]
    N186[test_benchmark.py]
    N187[test_bootstrap_skill.py]
    N188[test_bootstrap_skill_e2e.py]
    N189[test_c3_integration.py]
    N190[test_chunking_integration.py]
    N191[test_cli_parsers.py]
    N192[test_cli_paths.py]
    N193[test_cloud_storage.py]
    N194[test_code_analyzer.py]
    N195[test_codebase_scraper.py]
    N196[test_config_extractor.py]
    N197[test_config_fetcher.py]
    N198[test_config_validation.py]
    N199[test_constants.py]
    N200[test_dependency_analyzer.py]
    N201[test_e2e_three_stream_pipeline.py]
    N202[test_embedding.py]
    N203[test_embedding_pipeline.py]
    N204[test_enhance_skill_local.py]
    N205[test_estimate_pages.py]
    N206[test_excluded_dirs_config.py]
    N207[test_framework_detection.py]
    N208[test_generate_router_github.py]
    N209[test_git_repo.py]
    N210[test_git_sources_e2e.py]
    N211[test_github_fetcher.py]
    N212[test_github_scraper.py]
    N213[test_guide_enhancer.py]
    N214[test_how_to_guide_builder.py]
    N215[test_incremental_updates.py]
    N216[test_install_agent.py]
    N217[test_install_multiplatform.py]
    N218[test_install_skill.py]
    N219[test_install_skill_e2e.py]
    N220[test_integration.py]
    N221[test_integration_adaptors.py]
    N222[test_issue_219_e2e.py]
    N223[test_issue_277_real_world.py]
    N224[test_language_detector.py]
    N225[test_llms_txt_detector.py]
    N226[test_llms_txt_downloader.py]
    N227[test_llms_txt_parser.py]
    N228[test_markdown_parsing.py]
    N229[test_mcp_fastmcp.py]
    N230[test_mcp_git_sources.py]
    N231[test_mcp_server.py]
    N232[test_mcp_vector_dbs.py]
    N233[test_merge_sources_github.py]
    N234[test_multi_source.py]
    N235[test_multilang_support.py]
    N236[test_package_skill.py]
    N237[test_package_structure.py]
    N238[test_parallel_scraping.py]
    N239[test_pattern_recognizer.py]
    N240[test_pdf_advanced_features.py]
    N241[test_pdf_extractor.py]
    N242[test_pdf_scraper.py]
    N243[test_pr144_concerns.py]
    N244[test_preset_system.py]
    N245[test_quality_checker.py]
    N246[test_quality_metrics.py]
    N247[test_rag_chunker.py]
    N248[test_rate_limit_handler.py]
    N249[test_real_world_fastmcp.py]
    N250[test_scraper_features.py]
    N251[test_server_fastmcp_http.py]
    N252[test_setup_scripts.py]
    N253[test_skip_llms_txt.py]
    N254[test_smart_summarization.py]
    N255[test_source_manager.py]
    N256[test_streaming_ingestion.py]
    N257[test_swift_detection.py]
    N258[test_terminal_detection.py]
    N259[test_test_example_extractor.py]
    N260[test_unified.py]
    N261[test_unified_analyzer.py]
    N262[test_unified_mcp_integration.py]
    N263[test_upload_integration.py]
    N264[test_upload_skill.py]
    N265[test_url_conversion.py]
    N266[test_utilities.py]